modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="nirvo_music_disc"
version="1.0.0"
displayName="Nirvo Guardians of Angels music disc"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Atomiz"

[[dependencies.nirvo_music_disc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




